version: '3.8'

services:
  # Obsidian Elite RAG MCP Server
  obsidian-elite-rag:
    build: .
    container_name: obsidian-elite-rag-server
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /path/to/your/obsidian/vault:/vault:ro  # Read-only mount for your vault
    depends_on:
      - qdrant
      - neo4j
    networks:
      - rag-network
    profiles:
      - full

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: obsidian-rag-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - rag-network
    profiles:
      - databases
      - full

  # Neo4j Knowledge Graph Database
  neo4j:
    image: neo4j:5.14
    container_name: obsidian-rag-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7688:7688"
    volumes:
      - ./data/neo4j:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS='["apoc","graph-data-science"]'
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
    networks:
      - rag-network
    profiles:
      - databases
      - full

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local